name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.4.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^4.0.6
  rxdart: ^0.28.0
  share_plus: ^6.3.0
  path_provider: ^2.0.11
